version: '3.8'
services:
  static-web-server:
    image: joseluisq/static-web-server:latest
    network_mode: host
    environment:
      - SERVER_PORT: "8432"
      - SERVER_ROOT: "/haproxy/challenges"
    volumes:
      - ./haproxy/challenges:/haproxy/challenges