
# sudo docker compose --file=./docker-compose.yml up --force-recreate --build

version: '3.8'
services:
  studio:
    build:
      context: ../ # path of parent directory
      dockerfile: ./studio/Dockerfile # path relative to context
    restart: "no"
    network_mode: "host"
    command: node ./server/index.mjs